apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: terraform-demo
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001  # Optional: specify a node port or let Kubernetes choose one
  selector:
    app: nginx  # Ensure this matches the label in your nginx deployment
