name: Terraform CI/CD

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        env:
          KUBE_CONFIG_PATH: ${{ secrets.KUBE_CONFIG_PATH }} # Store kubeconfig as a secret
        run: terraform apply -auto-approve

      - name: Verify Deployment
        run: kubectl get all -n terraform-demo
